dist: xenial
sudo: false
language: python
cache: pip
python: 3.6
os:
  - linux
#  - osx
env:
  - TOX_ENV=py36
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
install:
  - pip install tox
  - pip install coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
